### ISSUE TITLE
Save settings and activities in localstorage

### ISSUE THREAD

**Issue by lifercode** [uzura89/pomodoro-timer#1]
This is the best and simplest pomodoro app I could find on the web.

The only problem is not saving settings and activities.

I want to help by contributing this!

**Comment by uzura89** [comment]
Hi, thank you for your comment.
However, I guess you are talking about https://pomofocus.io, which is different from this repository and its source code is not open. 

And right, it doesn't save settings and activities. 
I'm creating pomofocus also for the sake of learning, so I think I will try to implement the local storage feature by myself. 

Anyway, this is the first comment I got from other developers on GitHub and I'm impressed. 
Thank you.

**Comment by lifercode** [comment]
Perfect.
When this feature is available send me an alert please.

**Comment by uzura89** [comment]
Ok, I will let you know once the feature is created.
Maybe within a week. :)
